// Generated by Cypress Author on 2026-10-08.
// Squelette vierge de spec E2E, à compléter.

describe('Page contact', () => {
  beforeEach(() => {
    // Page de départ de chaque test (baseUrl = http://localhost:3000)
    cy.visit('http://localhost:3000/contact')
    // Indispensable avec Nuxt : attendre l'hydratation avant de cliquer ou saisir.
    // Vue pose __vue_app__ sur #__nuxt une fois l'application montée (= hydratée).
    cy.get('#__nuxt').should(($root) => {
      expect(($root[0] as HTMLElement & { __vue_app__?: unknown }).__vue_app__).to.exist
    })
  })

  // Generated by Cypress Author on 2026-10-08.
  it("Vérifier si un message d'erreur s'affiche quand le mail n'est pas conforme ", () => {
    cy.contains('label', 'test').click()
    cy.get('#firstName').type('Jack')
    cy.get('#lastName').type('Sparrow')
    cy.get('#email').type('JackSparrow')
    cy.get('#subject').type('Je suis un pirate')
    cy.get('#message').type('Il y a plus de Rhum !!!!')
    cy.contains('label', "J'accepte").click()
    cy.contains('button', " Envoyer le message").click()

    // Vérifications : sans elles, le test passe dès que les clics ont réussi
    cy.get('#error-email').should('contain', 'Veuillez saisir une adresse e-mail valide.')
    cy.contains('Votre message a bien été envoyé').should('not.exist')
  })

  it(`appuyer sur Tab le focus parcourt le formulaire dans l'ordre`, () => {
    cy.get('input[name="recipient"]').first().focus()

    cy.press(Cypress.Keyboard.Keys.TAB)
    cy.get('#firstName').should('have.focus')
    cy.press(Cypress.Keyboard.Keys.TAB)
    cy.get('#lastName').should('have.focus')
    cy.press(Cypress.Keyboard.Keys.TAB)
    cy.get('#email').should('have.focus')
    cy.press(Cypress.Keyboard.Keys.TAB)
    cy.get('#subject').should('have.focus')
    cy.press(Cypress.Keyboard.Keys.TAB)
    cy.get('#message').should('have.focus')
    cy.press(Cypress.Keyboard.Keys.TAB)
    cy.get('#gdpr').should('have.focus')
    cy.press(Cypress.Keyboard.Keys.TAB)
    cy.contains('a', 'contact@yolovi.fr').should('have.focus')
    cy.press(Cypress.Keyboard.Keys.TAB)
    cy.contains('button', 'Envoyer le message').should('have.focus')
  })
  
})

// Aide-mémoire Cypress :
//   cy.get('#id') / cy.get('[name="x"]')        sélectionner un élément (privilégier id, name, data-cy)
//   cy.contains('label', 'Texte').click()        sélectionner par texte visible
//   .type('texte') / .clear() / .check()         interagir
//   .should('be.visible') / ('have.value', 'x') / ('contain', 'x') / ('be.disabled')
//   cy.intercept('POST', '/api/contact', { statusCode: 200, body: {} }).as('envoi')
//   cy.wait('@envoi').its('request.body').should('deep.equal', { ... })
//   cy.request({ method: 'POST', url: '/api/contact', body: {...}, failOnStatusCode: false })
//   Jamais de cy.wait(5000) : les assertions réessaient automatiquement.
//
// Lancer : npm run cy:open (interface, serveur dev lancé à côté) ou npm run test:e2e
